[package]
name = "conway"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = { version = "0.8.5" }

[dev-dependencies]
criterion = { version = "0.4" }

[[bench]]
name = "state_update"
harness = false
