version: "3.9"

services:
  app:
    build:
      context: .
    image: tikhoplav/convay
    working_dir: /app
    volumes:
      - ./:/app
      - ./cache:/usr/local/cargo/registry
    ports:
      - 80:80
    command: ['cargo', 'run']
