[package]
name = "web"
version = "0.0.1"
edition = "2021"



[dependencies.conway]
path = "../../"

[dependencies.warp]
version = "0.3"

[dependencies.tokio]
version = "1.16"
features = ["full"]

[dependencies.futures-util]
version = "0.3"
default-features = false
features = ["sink"]



[[bin]]
name = "web"
path = "src/main.rs"



[profile.release]
lto = true
otp-level = 3
