[package]
name = "perfsim"
version = "0.0.1"
edition = "2021"

[dependencies]
conway = { path = "../../" }

[[bin]]
name = "perfsim"
path = "src/main.rs"

[profile.release]
debug = 1
lto = true
codegen-units = 1
opt-level = 3
